---
title: "Reading Data from Web"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
```

## NASOUH Data
```{r, warning = FALSE}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

#goes to the internet
drug_use_html =
  read_html(url) 

#goes to local directory
drug_use_html %>% 
  html_table() %>% 
  first() %>% 
  slice(-1) %>% view()
 
```


## Star War
Get some star war data


```{r}
sw_url = "https://www.imdb.com/list/ls070150896/"

sw_html = read_html(sw_url)

sw_titles = 
  sw_html %>% 
  html_elements(".lister-item-header a") %>%
  html_text()

sw_revenue = 
  sw_html %>% 
  html_elements(".text-small:nth-child(7) span:nth-child(5)") %>% 
  html_text()

sm_df = 
  tibble(
    title = sw_titles,
    revenue = sw_revenue
  )
```


## Dynamite review
```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

dynamite_review_titles = 
  dynamite_html %>%
  html_elements(".a-text-bold span") %>%
  html_text()

dynamite_stars = 
  dynamite_html %>%
  html_elements("#cm_cr-review_list .review-rating") %>%
  html_text()

dynamite_df = 
  tibble(
    titles = dynamite_review_titles,
    stars = dynamite_stars
  )
```


## API

#get some data from an API about water
```{r}
water_df1 = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content()
```


let's see what JSON looks like....
```{r}
water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% 
  content("text") %>% 
  jsonlite::fromJSON() %>% 
  as_tibble()
```
 

BRFSS data vis API
```{r}
brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% 
  content()
```

pokemon data
```{r}
poke_data = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke_data[["name"]]
poke_data[["height"]]
poke_data[["abilities"]]
```


